import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Bundled dictionary data is derived from ECDICT:
https://github.com/skywind3000/ECDICT

MIT License
Copyright (c) 2025 Linwei
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
`;

const prod = process.argv[2] === 'production';
const dictionaryFiles = [
	{
		name: 'glean-dict-v1.tsv',
		path: 'data/generated/glean-dict-v1.tsv',
	},
	{
		name: 'glean-inflect-v1.tsv',
		path: 'data/generated/glean-inflect-v1.tsv',
	},
];

const bundledDictionaryPlugin = {
	name: 'bundled-dictionary',
	setup(build) {
		build.onResolve({ filter: /^glean:dictionary-package$/ }, () => ({
			path: 'dictionary-package',
			namespace: 'glean',
		}));
		build.onLoad({ filter: /.*/, namespace: 'glean' }, async () => {
			if (!prod) {
				return {
					loader: 'js',
					contents: 'export const bundledDictionary = null;',
				};
			}
			const files = await Promise.all(
				dictionaryFiles.map(async (file) => {
					const data = await readFile(file.path);
					return {
						name: file.name,
						bytes: data.byteLength,
						sha256: createHash('sha256').update(data).digest('hex'),
						gzipBase64: gzipSync(data, { level: 9 }).toString('base64'),
					};
				}),
			);
			return {
				loader: 'js',
				contents: `export const bundledDictionary = ${JSON.stringify({
					version: 1,
					files,
				})};`,
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	plugins: [bundledDictionaryPlugin],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
		...builtinModules.map((module) => `node:${module}`),
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
